spring.application.name=quangvinhstore

server.port=9999

#Data source configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/quangvinhauthentic
spring.datasource.username=llbigcat
spring.datasource.password=Long2203@@
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

#Logging setting
spring.main.banner-mode=off
logging.level.org.springframework.security=DEBUG

#Jwt key and expiration time
app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app.jwt-expiration-milliseconds=604800000

#Backblaze image storage
b2.applicationKeyId=005d18819f5c56d0000000001
b2.applicationKey=K005bxpWOdEnxKpgIn8OHwq/r9uYYm0
b2.bucketId=ddb1080871f98f159c75061d

#Config for send multipart file
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=65MB
spring.servlet.multipart.max-request-size=75MB

# Swagger UI custom path
springdoc.swagger-ui.path=/swagger-ui.html
# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
# API docs path
springdoc.api-docs.path=/v3/api-docs