spring.application.name=quangvinhstore

server.port=9999

#Data source configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/quangvinhauthentic
spring.datasource.username=llbigcat
spring.datasource.password=Long2203@@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Logging setting
spring.main.banner-mode=off
logging.level.org.springframework.security=DEBUG

#Jwt key and expiration time
app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app.jwt-expiration-milliseconds=604800000

#Config for send multipart file
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=65MB
spring.servlet.multipart.max-request-size=75MB

# Swagger UI custom path
springdoc.swagger-ui.path=/swagger-ui.html
# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
# API docs path
springdoc.api-docs.path=/v3/api-docs

#Azure config
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=llbigcat;AccountKey=OZp8mJ0ExmYQcQjEFJ3LgL/U+TMaqNWcZy7sTr4nvMkuZc+/YTHePWQCdRFAaRETI7qR0vIEo691+ASt52qzfA==;EndpointSuffix=core.windows.net
azure.storage.container-name=quangvinhauthentic
