spring.application.name=quangvinhstore

server.port=9999

#Data source configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quangvinhauthentic
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Logging setting
spring.main.banner-mode=off
logging.level.org.springframework.security=DEBUG

#Jwt key and expiration time
app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app.jwt-expiration-milliseconds=604800000

#Config for send multipart file
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=65MB
spring.servlet.multipart.max-request-size=75MB

# Swagger UI custom path
springdoc.swagger-ui.path=/swagger-ui.html
# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
# API docs path
springdoc.api-docs.path=/v3/api-docs

#Azure config
azure.storage.connection-string=DefaultEndpointsProtocol=https;AccountName=llbigcat;AccountKey=+9DGoj7g5Frhd4zPmhvBYrYuxY/ZskSGSkthhpzqAU1XihuGIs3hpo57t5d3m9UQh4g0UY6JrdrY+AStjXrjwQ==;EndpointSuffix=core.windows.net
azure.storage.container-name=quangvinhauthentic

#Google API Login
spring.security.oauth2.client.registration.google.client-id=1054851040903-qtak8ih1gt3cqdsqg3sup0ufidbi65do.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

#GG Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duong23062003@gmail.com
spring.mail.password=uugm ltsq cslp edmq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Facebook API Login
spring.security.oauth2.client.registration.facebook.client-id=567181506220733
spring.security.oauth2.client.registration.facebook.client-secret=a6248e6bf720ad4f24e01c6828b6d550
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8081/auth-facebook/login
spring.security.oauth2.client.registration.facebook.scope=public_profile,email
spring.security.oauth2.client.registration.facebook.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v12.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v12.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email
spring.security.oauth2.client.provider.facebook.user-name-attribute=id

#Twilio
#twilio.account.sid=AC97453dffdb8b4e5b72e8b2702d1354f6
#twilio.auth.token=5b58b1b1cd91ee35be2b0905662a3a10
#twilio.phone.number=+15064368617

#twilio.account.sid=AC7f47a448d910f262709ecca0c5592be5
#twilio.auth.token=fcceb787ed5d0b3aea7ff5f1a981604e
#twilio.phone.number=+18565563480

twilio.account.sid=ACd3caffb110a9f02d6b083a04bdcd5879
twilio.auth.token=49686f6458a8b9ef7ed55d36585096cd
twilio.phone.number=+18565563480

#Firebase
firebase.service.account.path=src/main/resources/firebase-service-account.json

# VNPay Sandbox Configuration
vnpay.tmn-code=EUI6XOSF
vnpay.hash-secret=2NR46G386B8774C9CSZTFQRP59460XQO
vnpay.api-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8081/payment-return

#Momo Sandbox Configuration
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.partner-code=MOMO
